@extends('layouts.admin')

@section('content')
@php
$tabs=['hero'=>'Hero','about'=>'About','mission'=>'Mission','vision'=>'Vision','values'=>'Values','impact'=>'Impact','projects'=>'Projects','gallery'=>'Gallery','events'=>'Events','testimonials'=>'Testimonials','team'=>'Team','blog'=>'Blog / News','volunteer'=>'Volunteer','memorial-banner'=>'Memorial Banner','donate-impact'=>'Donation Impact','partners'=>'Partners & Sponsors','cta'=>'Call to Action','info-cards'=>'Info Cards'];
$section=$sections->keyBy('key')->get($activeTab);$content=$section?->contents->first();
$items=match($activeTab){'gallery'=>$galleryItems,'events'=>$events,'testimonials'=>$testimonials,'team'=>$teamMembers,'info-cards'=>$infoCards,'values'=>$section?->contents??collect(),default=>collect()};
$singleTabs=['hero','about','mission','vision','volunteer','memorial-banner','donate-impact','cta'];
$single=in_array($activeTab,$singleTabs,true);
$allowCreate=!$single && $activeTab !== 'blog';
@endphp
<style>
.cms-page{max-width:1500px;margin:auto}.cms-head{align-items:end;display:flex;justify-content:space-between;gap:1rem;margin-bottom:1rem}.cms-head h1{color:var(--text-strong);font-size:2rem;margin:.25rem 0}.cms-head p{color:var(--text-muted);margin:0}.cms-actions{display:flex;flex-wrap:wrap;gap:.5rem}.cms-tabs,.cms-card{background:var(--surface);border:1px solid var(--gray-200);border-radius:12px;box-shadow:0 8px 25px rgba(15,23,42,.05)}.cms-tabs{display:flex;gap:.25rem;margin-bottom:1rem;overflow:auto;padding:.5rem}.cms-tab{border-radius:8px;color:var(--text-muted);font-size:.8rem;font-weight:700;padding:.65rem .75rem;text-decoration:none;white-space:nowrap}.cms-tab.active,.cms-tab:hover{background:var(--primary-glow);color:var(--primary-dark)}.cms-card{padding:1.25rem}.cms-card h2{color:var(--text-strong);font-size:1.1rem;margin:0}.cms-card p{color:var(--text-muted);font-size:.84rem}.cms-table-wrap{border:1px solid var(--gray-200);border-radius:9px;overflow:auto}.cms-table{border-collapse:collapse;min-width:700px;width:100%}.cms-table th{background:var(--gray-50);color:var(--text-muted);font-size:.7rem;padding:.75rem;text-align:left;text-transform:uppercase}.cms-table td{border-top:1px solid var(--gray-200);color:var(--text-body);font-size:.84rem;padding:.8rem;vertical-align:middle}.cms-status{border-radius:999px;font-size:.7rem;font-weight:800;padding:.3rem .55rem}.cms-status.active{background:#dcfce7;color:#166534}.cms-status.hidden{background:#f1f5f9;color:#475569}.cms-action{align-items:center;background:var(--surface);border:1px solid var(--gray-300);border-radius:6px;color:var(--text-body);display:inline-flex;font-size:.73rem;gap:.3rem;padding:.35rem .5rem;text-decoration:none}.cms-action:hover{border-color:var(--primary);color:var(--primary)}.cms-action-primary{border-color:var(--primary);color:var(--primary)}.cms-action-danger{color:var(--danger)}.cms-action-danger:hover{border-color:var(--danger);color:var(--danger)}.cms-empty{color:var(--text-muted);padding:2rem;text-align:center}.cms-alert{border-radius:9px;margin-bottom:1rem;padding:.8rem}.cms-alert.success{background:#ecfdf5;color:#065f46}.cms-alert.error{background:#fef2f2;color:#991b1b}@media(max-width:700px){.cms-head{align-items:stretch;flex-direction:column}.cms-actions .btn-primary,.cms-actions .btn-secondary{justify-content:center;width:100%}.cms-action{margin-bottom:.25rem}}
</style>

<div class="cms-page">
<header class="cms-head"><div><div style="color:var(--primary);font-size:.72rem;font-weight:800;letter-spacing:.12em;text-transform:uppercase">Website content</div><h1>Manage {{ $tabs[$activeTab] ?? 'Content' }}</h1><p>{{ $section?->description ?: 'Manage and publish this landing page section.' }}</p></div><div class="cms-actions">@if($allowCreate)<a class="btn-primary" href="{{ route('admin.cms.index',['tab'=>$activeTab,'action'=>'create']) }}"><i class="fas fa-plus"></i> Add {{ $tabs[$activeTab] }}</a>@endif @if($section)<a class="btn-secondary" href="{{ route('admin.cms.index',['tab'=>$activeTab,'action'=>'section-title']) }}"><i class="fas fa-heading"></i> Update Section Title</a>@endif</div></header>
@if(session('success'))<div class="cms-alert success">{{ session('success') }}</div>@endif
@if(session('error'))<div class="cms-alert error">{{ session('error') }}</div>@endif
<nav class="cms-tabs">@foreach($tabs as $key=>$label)<a class="cms-tab {{ $activeTab===$key?'active':'' }}" href="{{ route('admin.cms.index',['tab'=>$key]) }}">{{ $label }}</a>@endforeach</nav>
<section class="cms-card"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:1rem"><div><h2>{{ $tabs[$activeTab] }}</h2><p>{{ $section?->description ?: 'Current records' }}</p></div></div>
@if($single)<div class="cms-table-wrap"><table class="cms-table"><thead><tr><th>Title</th><th>Description</th><th>Image</th><th>Status</th><th>Actions</th></tr></thead><tbody><tr><td>{{ $content?->title ?: 'Not configured' }}</td><td>{{ $content?->description ?: 'No content yet' }}</td><td>{{ $content?->image ? 'Uploaded' : 'None' }}</td><td><span class="cms-status {{ $content?->is_active?'active':'hidden' }}">{{ $content?->is_active?'Active':'Not configured' }}</span></td><td><a class="cms-action cms-action-primary" href="{{ route('admin.cms.index',['tab'=>$activeTab,'action'=>'edit']) }}"><i class="fas fa-pen"></i> Update</a></td></tr></tbody></table></div>
@elseif($activeTab==='impact')<div class="cms-table-wrap"><table class="cms-table"><thead><tr><th>Level</th><th>Title</th><th>Order</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($impactLevels as $item)<tr><td>{{ $item->level }}</td><td>{{ $item->title }}</td><td>{{ $item->sort_order }}</td><td><span class="cms-status {{ $item->is_active?'active':'hidden' }}">{{ $item->is_active?'Active':'Hidden' }}</span></td><td><a class="cms-action" href="{{ route('admin.cms.index',['tab'=>'impact','action'=>'view','edit_type'=>'impact','edit'=>$item->id]) }}"><i class="fas fa-eye"></i> View</a> <a class="cms-action cms-action-primary" href="{{ route('admin.cms.index',['tab'=>'impact','action'=>'edit','edit_type'=>'impact','edit'=>$item->id]) }}"><i class="fas fa-pen"></i> Edit</a><form method="POST" action="{{ route('admin.cms.items.destroy',['type'=>'impact','id'=>$item->id]) }}" style="display:inline" onsubmit="return confirm('Delete this impact level? This cannot be undone.')">@csrf @method('DELETE')<button class="cms-action cms-action-danger" type="submit"><i class="fas fa-trash"></i> Delete</button></form></td></tr>@empty<tr><td colspan="5"><div class="cms-empty">No impact levels have been added yet.</div></td></tr>@endforelse</tbody></table></div>
@elseif($activeTab==='projects')<div class="cms-table-wrap"><table class="cms-table"><thead><tr><th>Project</th><th>Goal</th><th>Raised</th><th>Progress</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($projects as $project)<tr><td>{{ $project->title }}</td><td>{{ number_format($project->goal_amount,2) }}</td><td>{{ number_format(min((float)($project->raised_total??0),(float)$project->goal_amount),2) }}</td><td>{{ number_format($project->goal_amount>0?min(((float)($project->raised_total??0)/$project->goal_amount)*100,100):0,1) }}%</td><td><span class="cms-status {{ $project->is_active?'active':'hidden' }}">{{ $project->is_active?'Active':'Hidden' }}</span></td><td><a class="cms-action" href="{{ route('admin.cms.index',['tab'=>'projects','action'=>'view','edit_project'=>$project->id]) }}"><i class="fas fa-eye"></i> View</a> <a class="cms-action cms-action-primary" href="{{ route('admin.cms.index',['tab'=>'projects','action'=>'edit','edit_project'=>$project->id]) }}"><i class="fas fa-pen"></i> Edit</a><form method="POST" action="{{ route('admin.cms.projects.destroy',$project) }}" style="display:inline" onsubmit="return confirm('Delete this project? This cannot be undone.')">@csrf @method('DELETE')<button class="cms-action cms-action-danger" type="submit"><i class="fas fa-trash"></i> Delete</button></form></td></tr>@empty<tr><td colspan="6"><div class="cms-empty">No projects have been added yet.</div></td></tr>@endforelse</tbody></table></div>
@elseif($activeTab==='blog')<div class="cms-table-wrap"><table class="cms-table"><thead><tr><th>Title</th><th>Category</th><th>Author</th><th>Published</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($blogPosts as $post)<tr><td>{{ $post->title }}</td><td>{{ $post->category }}</td><td>{{ $post->author }}</td><td>{{ optional($post->published_at)->format('M j, Y')?:'Draft' }}</td><td><span class="cms-status {{ $post->status === 'published' ? 'active' : 'hidden' }}">{{ ucfirst($post->status) }}</span></td><td><a class="cms-action" href="{{ route('blog.show',$post->slug) }}" target="_blank" rel="noopener">View</a></td></tr>@empty<tr><td colspan="6"><div class="cms-empty">No posts have been added yet.</div></td></tr>@endforelse</tbody></table></div>
@elseif($activeTab==='values')<div class="cms-table-wrap"><table class="cms-table"><thead><tr><th>Title</th><th>Description</th><th>Icon</th><th>Order</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($items as $item)<tr><td>{{ $item->title }}</td><td>{{ $item->description }}</td><td>{{ $item->metadata['icon']??'fa-heart' }}</td><td>{{ $item->sort_order }}</td><td><span class="cms-status {{ $item->is_active?'active':'hidden' }}">{{ $item->is_active?'Active':'Hidden' }}</span></td><td><a class="cms-action" href="{{ route('admin.cms.index',['tab'=>'values','action'=>'view','edit_type'=>'values','edit'=>$item->id]) }}"><i class="fas fa-eye"></i> View</a> <a class="cms-action cms-action-primary" href="{{ route('admin.cms.index',['tab'=>'values','action'=>'edit','edit_type'=>'values','edit'=>$item->id]) }}"><i class="fas fa-pen"></i> Edit</a><form method="POST" action="{{ route('admin.cms.sections.values.destroy',[$section,$item]) }}" style="display:inline" onsubmit="return confirm('Delete this value? This cannot be undone.')">@csrf @method('DELETE')<button class="cms-action cms-action-danger" type="submit"><i class="fas fa-trash"></i> Delete</button></form></td></tr>@empty<tr><td colspan="6"><div class="cms-empty">No values have been added yet.</div></td></tr>@endforelse</tbody></table></div>
@else<div class="cms-table-wrap"><table class="cms-table"><thead><tr><th>Record</th><th>Order</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($items as $item)<tr><td>@if($activeTab === 'partners')<img class="cms-thumbnail" src="{{ asset('storage/'.$item->logo) }}" alt="{{ $item->name }} logo"> <strong>{{ $item->name }}</strong>@else{{ $item->title??$item->name??$item->author_name??$item->badge }}@endif</td><td>{{ $item->sort_order }}</td><td><span class="cms-status {{ $item->is_active?'active':'hidden' }}">{{ $item->is_active?'Active':'Hidden' }}</span></td><td><a class="cms-action" href="{{ route('admin.cms.index',['tab'=>$activeTab,'action'=>'view','edit_type'=>$activeTab,'edit'=>$item->id]) }}"><i class="fas fa-eye"></i> View</a> <a class="cms-action cms-action-primary" href="{{ route('admin.cms.index',['tab'=>$activeTab,'action'=>'edit','edit_type'=>$activeTab,'edit'=>$item->id]) }}"><i class="fas fa-pen"></i> Edit</a><form method="POST" action="{{ route('admin.cms.items.destroy',['type'=>$activeTab,'id'=>$item->id]) }}" style="display:inline" onsubmit="return confirm('Delete this record? This cannot be undone.')">@csrf @method('DELETE')<button class="cms-action cms-action-danger" type="submit"><i class="fas fa-trash"></i> Delete</button></form></td></tr>@empty<tr><td colspan="4"><div class="cms-empty">No records have been added yet.</div></td></tr>@endforelse</tbody></table></div>@endif
</section></div>
@endsection
